# **Data Warehouse Script**

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **Data Fakta**

In [113]:
df = pd.read_csv("C:/Users/lenovo/Downloads/Data_Fakta_Kasus.csv")
df

,id_kasus,id_klien,id_pengacara,id_waktu,jenis_kasus,sub_jenis,teks_asli,durasi_hari,biaya_kasus,skor_kepuasan,id_lokasi
0,1,158,208,397,Ketenagakerjaan,PHK Sepihak,Perkara ini melibatkan PHK Sepihak dengan nila...,88,16287597,1,7
1,2,164,211,324,Ketenagakerjaan,PHK Sepihak,Sidang kasus PHK Sepihak telah ditunda karena ...,55,14383781,10,4
2,3,190,209,372,Pidana,Penipuan,Perselisihan terjadi antara dua pihak mengenai...,34,18637464,8,8
3,4,172,208,389,Ketenagakerjaan,PHK Sepihak,"Dalam kasus PHK Sepihak, terdakwa dituntut den...",101,5578587,2,5
4,5,138,208,352,Perdata,Wanprestasi,Sidang kasus Wanprestasi telah ditunda karena ...,94,20879986,9,7
...,...,...,...,...,...,...,...,...,...,...,...
95,96,199,218,395,Pidana,Penipuan,Pengacara menyatakan bahwa tidak ada cukup buk...,53,17640621,3,10
96,97,121,206,389,Perdata,Sengketa Tanah,Perkara ini melibatkan Sengketa Tanah dengan n...,66,17223859,4,9
97,98,157,220,337,Ketenagakerjaan,PHK Sepihak,Firma hukum menerima kasus baru terkait PHK Se...,78,20737552,4,7
98,99,148,219,357,Ketenagakerjaan,PHK Sepihak,Perkara ini melibatkan PHK Sepihak dengan nila...,46,10437769,4,9
99,100,178,205,333,Pidana,Penipuan,Gugatan perdata diajukan oleh klien terkait ka...,71,22311046,2,8

### **Data Dimensi**

In [115]:
df2 = pd.read_csv("C:/Users/lenovo/Downloads/Dim_Klien.csv")
df2

    id_klien      nama  usia jenis_kelamin      kota          provinsi
0          1   Klien 1    20     Laki-laki     Medan        Jawa Barat
1          2   Klien 2    18     Laki-laki   Bandung  Sulawesi Selatan
2          3   Klien 3    22     Laki-laki   Jakarta       DKI Jakarta
3          4   Klien 4    43     Laki-laki  Surabaya    Sumatera Utara
4          5   Klien 5    31     Perempuan     Medan        Jawa Barat
5          6   Klien 6    56     Perempuan     Medan        Jawa Barat
6          7   Klien 7    44     Perempuan   Bandung        Jawa Barat
7          8   Klien 8    26     Perempuan   Jakarta    Sumatera Utara
8          9   Klien 9    32     Perempuan  Surabaya    Sumatera Utara
9         10  Klien 10    32     Perempuan   Jakarta       DKI Jakarta
10        11  Klien 11    43     Laki-laki  Surabaya        Jawa Barat
11        12  Klien 12    59     Laki-laki  Surabaya  Sulawesi Selatan
12        13  Klien 13    30     Laki-laki   Bandung  Sulawesi Selatan
13        14  Klien 14    68     Perempuan  Surabaya        Jawa Timur
14        15  Klien 15    49     Laki-laki  Surabaya  Sulawesi Selatan
15        16  Klien 16    56     Perempuan   Jakarta    Sumatera Utara
16        17  Klien 17    66     Laki-laki   Bandung        Jawa Barat
17        18  Klien 18    69     Laki-laki  Makassar        Jawa Barat
18        19  Klien 19    49     Laki-laki  Makassar  Sulawesi Selatan
19        20  Klien 20    21     Perempuan   Bandung       DKI Jakarta
20        21  Klien 21    47     Perempuan   Jakarta       DKI Jakarta
21        22  Klien 22    54     Laki-laki   Bandung    Sumatera Utara
22        23  Klien 23    40     Laki-laki   Bandung       DKI Jakarta
23        24  Klien 24    56     Perempuan   Bandung        Jawa Timur
24        25  Klien 25    62     Perempuan   Bandung        Jawa Barat
25        26  Klien 26    32     Perempuan  Makassar        Jawa Barat
26        27  Klien 27    60     Perempuan     Medan       DKI Jakarta
27        28  Klien 28    46     Perempuan  Makassar  Sulawesi Selatan
28        29  Klien 29    53     Laki-laki     Medan       DKI Jakarta
29        30  Klien 30    30     Perempuan  Makassar        Jawa Barat
30        31  Klien 31    49     Perempuan     Medan    Sumatera Utara
31        32  Klien 32    24     Perempuan   Bandung       DKI Jakarta
32        33  Klien 33    68     Perempuan     Medan  Sulawesi Selatan
33        34  Klien 34    39     Perempuan  Makassar       DKI Jakarta
34        35  Klien 35    45     Laki-laki   Bandung        Jawa Timur
35        36  Klien 36    19     Laki-laki  Makassar  Sulawesi Selatan
36        37  Klien 37    59     Laki-laki  Surabaya  Sulawesi Selatan
37        38  Klien 38    62     Laki-laki  Makassar    Sumatera Utara
38        39  Klien 39    23     Perempuan  Surabaya        Jawa Barat
39        40  Klien 40    45     Laki-laki   Jakarta    Sumatera Utara
40        41  Klien 41    45     Perempuan     Medan        Jawa Timur
41        42  Klien 42    61     Laki-laki  Surabaya       DKI Jakarta
42        43  Klien 43    61     Laki-laki   Bandung        Jawa Timur
43        44  Klien 44    37     Perempuan  Surabaya       DKI Jakarta
44        45  Klien 45    47     Perempuan   Jakarta       DKI Jakarta
45        46  Klien 46    28     Perempuan  Surabaya        Jawa Timur
46        47  Klien 47    45     Laki-laki   Jakarta    Sumatera Utara
47        48  Klien 48    42     Perempuan  Surabaya        Jawa Timur
48        49  Klien 49    56     Laki-laki     Medan        Jawa Barat
49        50  Klien 50    50     Perempuan   Jakarta        Jawa Barat

In [116]:
df3 = pd.read_csv("C:/Users/lenovo/Downloads/Dim_Waktu.csv")
df3

    id_waktu     tanggal     bulan  tahun
0          1  2020-01-01   January   2020
1          2  2020-01-08   January   2020
2          3  2020-01-15   January   2020
3          4  2020-01-22   January   2020
4          5  2020-01-29   January   2020
..       ...         ...       ...    ...
95        96  2021-10-27   October   2021
96        97  2021-11-03  November   2021
97        98  2021-11-10  November   2021
98        99  2021-11-17  November   2021
99       100  2021-11-24  November   2021

[100 rows x 4 columns]

### Transformation data

In [119]:
df2 = pd.read_csv("C:/Users/lenovo/Downloads/Dim_Klien.csv")

df2 = df2.drop(columns=['id_klien'])  # Ensure the result is assigned back to df2
df2

        nama  usia jenis_kelamin      kota          provinsi
0    Klien 1    20     Laki-laki     Medan        Jawa Barat
1    Klien 2    18     Laki-laki   Bandung  Sulawesi Selatan
2    Klien 3    22     Laki-laki   Jakarta       DKI Jakarta
3    Klien 4    43     Laki-laki  Surabaya    Sumatera Utara
4    Klien 5    31     Perempuan     Medan        Jawa Barat
5    Klien 6    56     Perempuan     Medan        Jawa Barat
6    Klien 7    44     Perempuan   Bandung        Jawa Barat
7    Klien 8    26     Perempuan   Jakarta    Sumatera Utara
8    Klien 9    32     Perempuan  Surabaya    Sumatera Utara
9   Klien 10    32     Perempuan   Jakarta       DKI Jakarta
10  Klien 11    43     Laki-laki  Surabaya        Jawa Barat
11  Klien 12    59     Laki-laki  Surabaya  Sulawesi Selatan
12  Klien 13    30     Laki-laki   Bandung  Sulawesi Selatan
13  Klien 14    68     Perempuan  Surabaya        Jawa Timur
14  Klien 15    49     Laki-laki  Surabaya  Sulawesi Selatan
15  Klien 16    56     Perempuan   Jakarta    Sumatera Utara
16  Klien 17    66     Laki-laki   Bandung        Jawa Barat
17  Klien 18    69     Laki-laki  Makassar        Jawa Barat
18  Klien 19    49     Laki-laki  Makassar  Sulawesi Selatan
19  Klien 20    21     Perempuan   Bandung       DKI Jakarta
20  Klien 21    47     Perempuan   Jakarta       DKI Jakarta
21  Klien 22    54     Laki-laki   Bandung    Sumatera Utara
22  Klien 23    40     Laki-laki   Bandung       DKI Jakarta
23  Klien 24    56     Perempuan   Bandung        Jawa Timur
24  Klien 25    62     Perempuan   Bandung        Jawa Barat
25  Klien 26    32     Perempuan  Makassar        Jawa Barat
26  Klien 27    60     Perempuan     Medan       DKI Jakarta
27  Klien 28    46     Perempuan  Makassar  Sulawesi Selatan
28  Klien 29    53     Laki-laki     Medan       DKI Jakarta
29  Klien 30    30     Perempuan  Makassar        Jawa Barat
30  Klien 31    49     Perempuan     Medan    Sumatera Utara
31  Klien 32    24     Perempuan   Bandung       DKI Jakarta
32  Klien 33    68     Perempuan     Medan  Sulawesi Selatan
33  Klien 34    39     Perempuan  Makassar       DKI Jakarta
34  Klien 35    45     Laki-laki   Bandung        Jawa Timur
35  Klien 36    19     Laki-laki  Makassar  Sulawesi Selatan
36  Klien 37    59     Laki-laki  Surabaya  Sulawesi Selatan
37  Klien 38    62     Laki-laki  Makassar    Sumatera Utara
38  Klien 39    23     Perempuan  Surabaya        Jawa Barat
39  Klien 40    45     Laki-laki   Jakarta    Sumatera Utara
40  Klien 41    45     Perempuan     Medan        Jawa Timur
41  Klien 42    61     Laki-laki  Surabaya       DKI Jakarta
42  Klien 43    61     Laki-laki   Bandung        Jawa Timur
43  Klien 44    37     Perempuan  Surabaya       DKI Jakarta
44  Klien 45    47     Perempuan   Jakarta       DKI Jakarta
45  Klien 46    28     Perempuan  Surabaya        Jawa Timur
46  Klien 47    45     Laki-laki   Jakarta    Sumatera Utara
47  Klien 48    42     Perempuan  Surabaya        Jawa Timur
48  Klien 49    56     Laki-laki     Medan        Jawa Barat
49  Klien 50    50     Perempuan   Jakarta        Jawa Barat

In [120]:

df.duplicated().sum()
print(f"jumlah data yang terduplikat: {df.duplicated().sum()}")

# Ambil kolom id_klien dari df dan pindahkan ke df2
df2['id_klien'] = df['id_klien']
df2

jumlah data yang terduplikat: 0

        nama  usia jenis_kelamin      kota          provinsi  id_klien
0    Klien 1    20     Laki-laki     Medan        Jawa Barat       158
1    Klien 2    18     Laki-laki   Bandung  Sulawesi Selatan       164
2    Klien 3    22     Laki-laki   Jakarta       DKI Jakarta       190
3    Klien 4    43     Laki-laki  Surabaya    Sumatera Utara       172
4    Klien 5    31     Perempuan     Medan        Jawa Barat       138
5    Klien 6    56     Perempuan     Medan        Jawa Barat       168
6    Klien 7    44     Perempuan   Bandung        Jawa Barat       130
7    Klien 8    26     Perempuan   Jakarta    Sumatera Utara       195
8    Klien 9    32     Perempuan  Surabaya    Sumatera Utara       123
9   Klien 10    32     Perempuan   Jakarta       DKI Jakarta       114
10  Klien 11    43     Laki-laki  Surabaya        Jawa Barat       133
11  Klien 12    59     Laki-laki  Surabaya  Sulawesi Selatan       173
12  Klien 13    30     Laki-laki   Bandung  Sulawesi Selatan       158
13  Klien 14    68     Perempuan  Surabaya        Jawa Timur       181
14  Klien 15    49     Laki-laki  Surabaya  Sulawesi Selatan       153
15  Klien 16    56     Perempuan   Jakarta    Sumatera Utara       110
16  Klien 17    66     Laki-laki   Bandung        Jawa Barat       119
17  Klien 18    69     Laki-laki  Makassar        Jawa Barat       160
18  Klien 19    49     Laki-laki  Makassar  Sulawesi Selatan       177
19  Klien 20    21     Perempuan   Bandung       DKI Jakarta       176
20  Klien 21    47     Perempuan   Jakarta       DKI Jakarta       136
21  Klien 22    54     Laki-laki   Bandung    Sumatera Utara       153
22  Klien 23    40     Laki-laki   Bandung       DKI Jakarta       185
23  Klien 24    56     Perempuan   Bandung        Jawa Timur       199
24  Klien 25    62     Perempuan   Bandung        Jawa Barat       167
25  Klien 26    32     Perempuan  Makassar        Jawa Barat       117
26  Klien 27    60     Perempuan     Medan       DKI Jakarta       171
27  Klien 28    46     Perempuan  Makassar  Sulawesi Selatan       164
28  Klien 29    53     Laki-laki     Medan       DKI Jakarta       171
29  Klien 30    30     Perempuan  Makassar        Jawa Barat       144
30  Klien 31    49     Perempuan     Medan    Sumatera Utara       169
31  Klien 32    24     Perempuan   Bandung       DKI Jakarta       125
32  Klien 33    68     Perempuan     Medan  Sulawesi Selatan       191
33  Klien 34    39     Perempuan  Makassar       DKI Jakarta       113
34  Klien 35    45     Laki-laki   Bandung        Jawa Timur       134
35  Klien 36    19     Laki-laki  Makassar  Sulawesi Selatan       170
36  Klien 37    59     Laki-laki  Surabaya  Sulawesi Selatan       113
37  Klien 38    62     Laki-laki  Makassar    Sumatera Utara       138
38  Klien 39    23     Perempuan  Surabaya        Jawa Barat       122
39  Klien 40    45     Laki-laki   Jakarta    Sumatera Utara       130
40  Klien 41    45     Perempuan     Medan        Jawa Timur       187
41  Klien 42    61     Laki-laki  Surabaya       DKI Jakarta       159
42  Klien 43    61     Laki-laki   Bandung        Jawa Timur       146
43  Klien 44    37     Perempuan  Surabaya       DKI Jakarta       173
44  Klien 45    47     Perempuan   Jakarta       DKI Jakarta       180
45  Klien 46    28     Perempuan  Surabaya        Jawa Timur       105
46  Klien 47    45     Laki-laki   Jakarta    Sumatera Utara       117
47  Klien 48    42     Perempuan  Surabaya        Jawa Timur       115
48  Klien 49    56     Laki-laki     Medan        Jawa Barat       102
49  Klien 50    50     Perempuan   Jakarta        Jawa Barat       187

In [121]:
# Membuat tabel baru untuk kota dan provinsi dari df2
kota_provinsi = df2[['kota', 'provinsi']].drop_duplicates().reset_index(drop=True)
kota_provinsi

        kota          provinsi
0      Medan        Jawa Barat
1    Bandung  Sulawesi Selatan
2    Jakarta       DKI Jakarta
3   Surabaya    Sumatera Utara
4    Bandung        Jawa Barat
5    Jakarta    Sumatera Utara
6   Surabaya        Jawa Barat
7   Surabaya  Sulawesi Selatan
8   Surabaya        Jawa Timur
9   Makassar        Jawa Barat
10  Makassar  Sulawesi Selatan
11   Bandung       DKI Jakarta
12   Bandung    Sumatera Utara
13   Bandung        Jawa Timur
14     Medan       DKI Jakarta
15     Medan    Sumatera Utara
16     Medan  Sulawesi Selatan
17  Makassar       DKI Jakarta
18  Makassar    Sumatera Utara
19     Medan        Jawa Timur
20  Surabaya       DKI Jakarta
21   Jakarta        Jawa Barat

In [122]:
df

,id_kasus,id_klien,id_pengacara,id_waktu,jenis_kasus,sub_jenis,teks_asli,durasi_hari,biaya_kasus,skor_kepuasan,id_lokasi
0,1,158,208,397,Ketenagakerjaan,PHK Sepihak,Perkara ini melibatkan PHK Sepihak dengan nila...,88,16287597,1,7
1,2,164,211,324,Ketenagakerjaan,PHK Sepihak,Sidang kasus PHK Sepihak telah ditunda karena ...,55,14383781,10,4
2,3,190,209,372,Pidana,Penipuan,Perselisihan terjadi antara dua pihak mengenai...,34,18637464,8,8
3,4,172,208,389,Ketenagakerjaan,PHK Sepihak,"Dalam kasus PHK Sepihak, terdakwa dituntut den...",101,5578587,2,5
4,5,138,208,352,Perdata,Wanprestasi,Sidang kasus Wanprestasi telah ditunda karena ...,94,20879986,9,7
...,...,...,...,...,...,...,...,...,...,...,...
95,96,199,218,395,Pidana,Penipuan,Pengacara menyatakan bahwa tidak ada cukup buk...,53,17640621,3,10
96,97,121,206,389,Perdata,Sengketa Tanah,Perkara ini melibatkan Sengketa Tanah dengan n...,66,17223859,4,9
97,98,157,220,337,Ketenagakerjaan,PHK Sepihak,Firma hukum menerima kasus baru terkait PHK Se...,78,20737552,4,7
98,99,148,219,357,Ketenagakerjaan,PHK Sepihak,Perkara ini melibatkan PHK Sepihak dengan nila...,46,10437769,4,9
99,100,178,205,333,Pidana,Penipuan,Gugatan perdata diajukan oleh klien terkait ka...,71,22311046,2,8

In [123]:
df2

        nama  usia jenis_kelamin      kota          provinsi  id_klien
0    Klien 1    20     Laki-laki     Medan        Jawa Barat       158
1    Klien 2    18     Laki-laki   Bandung  Sulawesi Selatan       164
2    Klien 3    22     Laki-laki   Jakarta       DKI Jakarta       190
3    Klien 4    43     Laki-laki  Surabaya    Sumatera Utara       172
4    Klien 5    31     Perempuan     Medan        Jawa Barat       138
5    Klien 6    56     Perempuan     Medan        Jawa Barat       168
6    Klien 7    44     Perempuan   Bandung        Jawa Barat       130
7    Klien 8    26     Perempuan   Jakarta    Sumatera Utara       195
8    Klien 9    32     Perempuan  Surabaya    Sumatera Utara       123
9   Klien 10    32     Perempuan   Jakarta       DKI Jakarta       114
10  Klien 11    43     Laki-laki  Surabaya        Jawa Barat       133
11  Klien 12    59     Laki-laki  Surabaya  Sulawesi Selatan       173
12  Klien 13    30     Laki-laki   Bandung  Sulawesi Selatan       158
13  Klien 14    68     Perempuan  Surabaya        Jawa Timur       181
14  Klien 15    49     Laki-laki  Surabaya  Sulawesi Selatan       153
15  Klien 16    56     Perempuan   Jakarta    Sumatera Utara       110
16  Klien 17    66     Laki-laki   Bandung        Jawa Barat       119
17  Klien 18    69     Laki-laki  Makassar        Jawa Barat       160
18  Klien 19    49     Laki-laki  Makassar  Sulawesi Selatan       177
19  Klien 20    21     Perempuan   Bandung       DKI Jakarta       176
20  Klien 21    47     Perempuan   Jakarta       DKI Jakarta       136
21  Klien 22    54     Laki-laki   Bandung    Sumatera Utara       153
22  Klien 23    40     Laki-laki   Bandung       DKI Jakarta       185
23  Klien 24    56     Perempuan   Bandung        Jawa Timur       199
24  Klien 25    62     Perempuan   Bandung        Jawa Barat       167
25  Klien 26    32     Perempuan  Makassar        Jawa Barat       117
26  Klien 27    60     Perempuan     Medan       DKI Jakarta       171
27  Klien 28    46     Perempuan  Makassar  Sulawesi Selatan       164
28  Klien 29    53     Laki-laki     Medan       DKI Jakarta       171
29  Klien 30    30     Perempuan  Makassar        Jawa Barat       144
30  Klien 31    49     Perempuan     Medan    Sumatera Utara       169
31  Klien 32    24     Perempuan   Bandung       DKI Jakarta       125
32  Klien 33    68     Perempuan     Medan  Sulawesi Selatan       191
33  Klien 34    39     Perempuan  Makassar       DKI Jakarta       113
34  Klien 35    45     Laki-laki   Bandung        Jawa Timur       134
35  Klien 36    19     Laki-laki  Makassar  Sulawesi Selatan       170
36  Klien 37    59     Laki-laki  Surabaya  Sulawesi Selatan       113
37  Klien 38    62     Laki-laki  Makassar    Sumatera Utara       138
38  Klien 39    23     Perempuan  Surabaya        Jawa Barat       122
39  Klien 40    45     Laki-laki   Jakarta    Sumatera Utara       130
40  Klien 41    45     Perempuan     Medan        Jawa Timur       187
41  Klien 42    61     Laki-laki  Surabaya       DKI Jakarta       159
42  Klien 43    61     Laki-laki   Bandung        Jawa Timur       146
43  Klien 44    37     Perempuan  Surabaya       DKI Jakarta       173
44  Klien 45    47     Perempuan   Jakarta       DKI Jakarta       180
45  Klien 46    28     Perempuan  Surabaya        Jawa Timur       105
46  Klien 47    45     Laki-laki   Jakarta    Sumatera Utara       117
47  Klien 48    42     Perempuan  Surabaya        Jawa Timur       115
48  Klien 49    56     Laki-laki     Medan        Jawa Barat       102
49  Klien 50    50     Perempuan   Jakarta        Jawa Barat       187

In [124]:
df = df.drop(index=range(50, 100)) 
df

,id_kasus,id_klien,id_pengacara,id_waktu,jenis_kasus,sub_jenis,teks_asli,durasi_hari,biaya_kasus,skor_kepuasan,id_lokasi
0,1,158,208,397,Ketenagakerjaan,PHK Sepihak,Perkara ini melibatkan PHK Sepihak dengan nila...,88,16287597,1,7
1,2,164,211,324,Ketenagakerjaan,PHK Sepihak,Sidang kasus PHK Sepihak telah ditunda karena ...,55,14383781,10,4
2,3,190,209,372,Pidana,Penipuan,Perselisihan terjadi antara dua pihak mengenai...,34,18637464,8,8
3,4,172,208,389,Ketenagakerjaan,PHK Sepihak,"Dalam kasus PHK Sepihak, terdakwa dituntut den...",101,5578587,2,5
4,5,138,208,352,Perdata,Wanprestasi,Sidang kasus Wanprestasi telah ditunda karena ...,94,20879986,9,7
5,6,168,212,355,Perceraian,Cerai Talak,Firma hukum menerima kasus baru terkait Cerai ...,99,15288560,5,10
6,7,130,204,393,Perdata,Wanprestasi,Pengacara menyatakan bahwa tidak ada cukup buk...,25,11427048,4,3
7,8,195,216,336,Perceraian,Cerai Gugat,Firma hukum menerima kasus baru terkait Cerai ...,116,12633068,6,7
8,9,123,210,302,Perdata,Sengketa Tanah,Firma hukum menerima kasus baru terkait Sengke...,15,9237236,8,8
9,10,114,201,374,Perceraian,Cerai Gugat,Sidang kasus Cerai Gugat telah ditunda karena ...,71,11186218,1,5
10,11,133,216,315,Pidana,Penggelapan,Terdakwa diduga melakukan Penggelapan terhadap...,72,10091113,3,4
11,12,173,210,311,Perdata,Wanprestasi,Perselisihan terjadi antara dua pihak mengenai...,81,22534624,7,8
12,13,158,215,339,Hak Cipta,Plagiarisme,Terdakwa diduga melakukan Plagiarisme terhadap...,82,8329726,4,8
13,14,181,207,334,Pidana,Penggelapan,Gugatan perdata diajukan oleh klien terkait ka...,40,10252363,1,3
14,15,153,215,389,Ketenagakerjaan,PHK Sepihak,Firma hukum menerima kasus baru terkait PHK Se...,14,14486454,8,6
15,16,110,208,334,Perdata,Wanprestasi,Perselisihan terjadi antara dua pihak mengenai...,24,9999254,5,5
16,17,119,203,308,Perdata,Sengketa Tanah,Firma hukum menerima kasus baru terkait Sengke...,49,19735544,2,2
17,18,160,210,390,Hak Cipta,Plagiarisme,"Dalam kasus Plagiarisme, terdakwa dituntut den...",74,19688750,2,8
18,19,177,202,356,Perceraian,Cerai Talak,Gugatan perdata diajukan oleh klien terkait ka...,42,12681428,10,6
19,20,176,201,398,Perceraian,Cerai Gugat,"Dalam kasus Cerai Gugat, terdakwa dituntut den...",15,22413536,8,2
20,21,136,206,375,Hak Cipta,Plagiarisme,Gugatan perdata diajukan oleh klien terkait ka...,114,20770931,6,5
21,22,153,211,342,Pidana,Penggelapan,Perkara ini melibatkan Penggelapan dengan nila...,30,21625181,5,1
22,23,185,213,398,Pidana,Penipuan,Firma hukum menerima kasus baru terkait Penipu...,21,15847268,2,10
23,24,199,213,366,Pidana,Penipuan,Perkara ini melibatkan Penipuan dengan nilai s...,79,6818787,4,6
24,25,167,212,380,Ketenagakerjaan,PHK Sepihak,Perselisihan terjadi antara dua pihak mengenai...,66,13960920,9,9
25,26,117,210,357,Ketenagakerjaan,PHK Sepihak,Perselisihan terjadi antara dua pihak mengenai...,13,10314289,5,1
26,27,171,201,371,Hak Cipta,Plagiarisme,"Dalam kasus Plagiarisme, terdakwa dituntut den...",38,8941509,3,10
27,28,164,210,366,Perceraian,Cerai Gugat,"Dalam kasus Cerai Gugat, terdakwa dituntut den...",116,13178252,8,3
28,29,171,205,350,Perdata,Wanprestasi,Gugatan perdata diajukan oleh klien terkait ka...,75,14269324,7,7
29,30,144,217,335,Pidana,Penipuan,"Dalam kasus Penipuan, terdakwa dituntut dengan...",102,9986034,8,4
30,31,169,216,345,Perceraian,Cerai Talak,Perkara ini melibatkan Cerai Talak dengan nila...,107,20278829,6,9
31,32,125,208,374,Hak Cipta,Plagiarisme,Terdakwa diduga melakukan Plagiarisme terhadap...,119,15676225,8,3
32,33,191,213,350,Perdata,Sengketa Tanah,Sidang kasus Sengketa Tanah telah ditunda kare...,14,8367677,8,5
33,34,113,217,359,Pidana,Penipuan,Pengacara menyatakan bahwa tidak ada cukup buk...,28,7510819,8,3
34,35,134,211,380,Hak Cipta,Plagiarisme,Perkara ini melibatkan Plagiarisme dengan nila...,20,15625385,8,7
35,36,170,202,380,Pidana,Penggelapan,Perselisihan terjadi antara dua pihak mengenai...,90,8032627,7,5
36,37,113,204,357,Perdata,Sengketa Tanah,Terdakwa diduga melakukan Sengketa Tanah terha...,48,15884207,1,9
37,38,138,212,348,Hak Cipta,Plagiarisme,Perkara ini melibatkan Plagiarisme dengan nila...,41,23989394,3,7
38,39,122,206,311,Hak Cipta,Plagiarisme,"Dalam kasus Plagiarisme, terdakwa dituntut den...",97,24567506,3,2
39,40,130,215,382,Perceraian,Cerai Gugat,Terdakwa diduga melakukan Cerai Gugat terhadap...,42,20611308,5,4
40,41,187,218,321,Pidana,Penggelapan,Firma hukum menerima kasus baru terkait Pengge...,54,19237445,5,9
41,42,159,210,326,Hak Cipta,Plagiarisme,Perselisihan terjadi antara dua pihak mengenai...,71,17796462,10,2
42,43,146,219,338,Perceraian,Cerai Gugat,Perkara ini melibatkan Cerai Gugat dengan nila...,116,14210033,1,10
43,44,173,202,378,Ketenagakerjaan,PHK Sepihak,Sidang kasus PHK Sepihak telah ditunda karena ...,46,12348572,4,9
44,45,180,209,387,Perdata,Sengketa Tanah,Terdakwa diduga melakukan Sengketa Tanah terha...,22,15366067,8,10
45,46,105,219,347,Perdata,Sengketa Tanah,Perkara ini melibatkan Sengketa Tanah dengan n...,47,10893502,4,5
46,47,117,218,347,Perceraian,Cerai Gugat,"Dalam kasus Cerai Gugat, terdakwa dituntut den...",31,14903303,6,2
47,48,115,215,310,Perdata,Sengketa Tanah,Sidang kasus Sengketa Tanah telah ditunda kare...,38,8030061,7,4
48,49,102,209,369,Pidana,Penggelapan,Perkara ini melibatkan Penggelapan dengan nila...,57,17464587,2,7
49,50,187,208,361,Pidana,Penipuan,Perselisihan terjadi antara dua pihak mengenai...,81,7121211,8,8

In [126]:
df3 = pd.read_csv("C:/Users/lenovo/Downloads/Dim_Waktu.csv")
# Hapus baris data 51-100
df3 = df3.drop(index=range(50, 100))  # Ensure the result is assigned back to df3
df3

    id_waktu     tanggal      bulan  tahun
0          1  2020-01-01    January   2020
1          2  2020-01-08    January   2020
2          3  2020-01-15    January   2020
3          4  2020-01-22    January   2020
4          5  2020-01-29    January   2020
5          6  2020-02-05   February   2020
6          7  2020-02-12   February   2020
7          8  2020-02-19   February   2020
8          9  2020-02-26   February   2020
9         10  2020-03-04      March   2020
10        11  2020-03-11      March   2020
11        12  2020-03-18      March   2020
12        13  2020-03-25      March   2020
13        14  2020-04-01      April   2020
14        15  2020-04-08      April   2020
15        16  2020-04-15      April   2020
16        17  2020-04-22      April   2020
17        18  2020-04-29      April   2020
18        19  2020-05-06        May   2020
19        20  2020-05-13        May   2020
20        21  2020-05-20        May   2020
21        22  2020-05-27        May   2020
22        23  2020-06-03       June   2020
23        24  2020-06-10       June   2020
24        25  2020-06-17       June   2020
25        26  2020-06-24       June   2020
26        27  2020-07-01       July   2020
27        28  2020-07-08       July   2020
28        29  2020-07-15       July   2020
29        30  2020-07-22       July   2020
30        31  2020-07-29       July   2020
31        32  2020-08-05     August   2020
32        33  2020-08-12     August   2020
33        34  2020-08-19     August   2020
34        35  2020-08-26     August   2020
35        36  2020-09-02  September   2020
36        37  2020-09-09  September   2020
37        38  2020-09-16  September   2020
38        39  2020-09-23  September   2020
39        40  2020-09-30  September   2020
40        41  2020-10-07    October   2020
41        42  2020-10-14    October   2020
42        43  2020-10-21    October   2020
43        44  2020-10-28    October   2020
44        45  2020-11-04   November   2020
45        46  2020-11-11   November   2020
46        47  2020-11-18   November   2020
47        48  2020-11-25   November   2020
48        49  2020-12-02   December   2020
49        50  2020-12-09   December   2020

In [127]:
# Save DataFrames to CSV files
df.to_csv("D:/script dw/df.csv", index=False)   # Save df to df.csv
df2.to_csv("D:/script dw/df2.csv", index=False) # Save df2 to df2.csv
df3.to_csv("D:/script dw/df3.csv", index=False) # Save df3 to df3.csv